[package]
name = "sui_counter"
version = "0.0.1"


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
counter_app =  "0x0"
sui="0x2"
