[package]
name = "sui_counter"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
sui_counter =  "0x0"
sui =  "0x0000000000000000000000000000000000000002"
